# 
# Plugin by ISweeZee 
# 
# Tout symbol utilisé par UTF-8 son autorisé dans minecraft !
# Pour change le skin du NPC vous devez changer la signature et texture !
# 
# Pour commencer, installez le skin souhaité et rendez-vous sur https://mineskin.org/ !
# Importez le skin en cliquant sur 'SELECT FILE' en cliquant sur 'GENERATE' 
# Deux "liens" apparaîtront 'Texture Value' qui correspond à la texture et l'autre à la signature !
# 
# 'true' make npcs loot at player
# 'false' make npcs look in their direction
npc: